c_compiler:
  - clang  # [linux]
  - clang  # [osx]
  - vs2022  # [win]
c_compiler_version:  # [unix]
  - 19  # [linux]
  - 22  # [osx]
cxx_compiler:
  - clangxx  # [linux]
  - vs2022  # [win]
  - clangxx  # [osx]
cxx_compiler_version:  # [unix]
  - 19  # [linux]
  - 22  # [osx]
microarch_level:
  - 1
  - 3  # [unix and x86_64]
