{% set name = "raspa3" %}
{% set version = "3.0.16" %}
{% set build = 0 %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/iRASPA/RASPA3/archive/v{{ version }}.tar.gz
  sha256: 41f56370f65f8954c0bfb4393086183f43e655d18511a2401544960003857f75

build:
  # Prioritize builds with a higher microarch level.
  number: {{ build }}  # [not (unix and x86_64)]
  number: {{ build + 100 }}  # [unix and x86_64 and microarch_level == 1]
  number: {{ build + 300 }}  # [unix and x86_64 and microarch_level == 3]

requirements:
  build:
    - x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clang-tools  # [osx]
    - llvm-tools  # [osx]
    - lld  # [osx]
    - libcxx-devel  # [osx]
    - cmake
    - ninja
    - gtest
  host:
    - libcxx  # [osx]
    - libgomp  # [linux]
    - llvm-openmp  # [not linux]
    - libblas
    - liblapack
    - hdf5
    - zlib
    - openssl
    - libcurl
    - libaec
    - libopencl-devel
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx and win]
    - fftw
  run:
    - ocl-icd  # [linux]
    - khronos-opencl-icd-loader  # [osx and win]
    - ocl_icd_wrapper_apple  # [osx]

test:
  commands:
    - raspa3 --help

about:
  home: https://github.com/iraspa/raspa3
  summary: 'A general purpose classical simulation package'
  description: |
    RASPA is a software package for simulating adsorption and 
    diffusion of molecules in flexible nanoporous materials. 
    The code implements the latest state-of-the-art algorithms 
    for Molecular Dynamics and Monte Carlo in various ensembles 
    including symplectic/measure-preserving integrators, Ewald 
    summation, Configurational-Bias Monte Carlo, Continuous 
    Fractional Component Monte Carlo, and Reactive Monte Carlo.
  license: MIT
  license_file: LICENSE.md
  doc_url: https://iraspa.github.io/RASPA3
  dev_url: https://github.com/iraspa/raspa3

extra:
  recipe-maintainers:
    - dubbelda
